
  
logging:
  level:
    root: "debug"
    org.springframework.web: "debug"
    org.hibernate: "error"
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ukream?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zxcv2213
